# Generated by Django 4.1 on 2022-08-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='userID',
            field=models.CharField(max_length=200),
        ),
    ]
